### ISSUE TITLE
nio-connect-proxy fails to send error response

### ISSUE THREAD

**Issue by nlevitt** [apple/swift-nio-examples#61]
### Expected behavior

On receiving a bad / unsupported request, return a 400 response

### Actual behavior

It just hangs, no response, and leaves the socket open.

### Steps to reproduce

1. Start the proxy
2. Try to fetch an http (not https) url through it
```
$ curl -gvsS --proxy localhost:8080 http://example.com/
```

### version/commit hashes from all involved dependencies

- swift-nio-examples 909a55edb479385c4a4c3b03b7b4a167e4965875
- swift-nio 2.18.0 120acb15c39aa3217e9888e515de160378fbcc1e
- swift-log 1.2.0 74d7b91ceebc85daf387ebb206003f78813f71aa

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0
Darwin Noahs-MacBook-Pro-16-inch-2019 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

**Comment by nlevitt** [comment]
I confirmed this function  gets called and finishes, but the `.whenComplete` callback is never called
https://github.com/apple/swift-nio-examples/blob/909a55e/connect-proxy/Sources/ConnectProxy/ConnectHandler.swift#L229
```
    private func httpErrorAndClose(context: ChannelHandlerContext) {
        self.upgradeState = .upgradeFailed

        let headers = HTTPHeaders([("Content-Length", "0"), ("Connection", "close")])
        let head = HTTPResponseHead(version: .init(major: 1, minor: 1), status: .badRequest, headers: headers)
        context.write(self.wrapOutboundOut(.head(head)), promise: nil)
        context.write(self.wrapOutboundOut(.end(nil))).whenComplete { (_: Result<Void, Error>) in
            context.close(mode: .output, promise: nil)
        }
    }
```

**Comment by Lukasa** [comment]
Yeah, I think there’s a flush missing on that path. We should just turn that last `write` into `writeAndFlush`.
