### ISSUE TITLE
Example of JSON RPC using blocking semantics?

### ISSUE THREAD

**Issue by tjprescott** [apple/swift-nio-examples#68]
We have a code generator for Swift that is based on the JSON RPC example here. However, the asynchronous nature is causing maintainability headaches for us. For example, we need to make several JSON RPC calls to retrieve values from the other process,  and we need to wait until all of the values have been successfully retrieved before we continue. Currently, the working solution for this produces an ugly pyramid-of-doom:

```swift
get(value: "1") {
  get(value: "2") {
    get(value: "3") {
       // etc. and then finally
      completion()
    }
  }
}
```

There are over a dozen values we need to get, so this is clearly not what we want. We really just want something like:
```swift
group = DispatchGroup()
for key in keys {
  group.enter()
  let future = channel.call(method: "GetValue": params: .list([.string(session), .string(key)]))
  future.whenSuccess { result in
    switch result {
      case let .success(response):
        let value = response.asString
        self.args[key] = value
      case .failure:
        break
    }
    group.leave()
  }
}
group.wait()
completion()
```

However, this just hangs. Trying to use `group.notify(DispatchQueue.global()) { completion() }` seemingly works but then the next RPC call fails:
```
Precondition failed: file /Users/.../.build/checkouts/swift-nio/Sources/NIO/ChannelPipeline.swift, line 158
```

The following PR in the swift-nio repo added convenience API for blocking semantics to Swift NIO: https://github.com/apple/swift-nio/issues/1563

Could you provide an example of how `Client.call(method:params)` (https://github.com/apple/swift-nio-examples/blob/main/json-rpc/Sources/JsonRpc/Client.swift#L60) can be rewritten to use these blocking semantics such that RPC calls are essentially synchronous?

**Comment by Lukasa** [comment]
There are several options, but the easiest one is to use the event loop futures directly to get quite close to your `DispatchGroup` based design. However, we need to be careful with threading: your use of `channel.call` in this code is likely to be unsafe unless you've already established event loop context. So we'll fix that up as well.

```swift
let callResults: [Result] = try channel.eventLoop.flatSubmit {
    let futures = keys.map { channel.call(method: "GetValue": params: .list([.string(session), .string($0)])) }
    return EventLoopFuture.whenAllSucceed(futures, on: channel.eventLoop)
}.wait()
```

**Comment by tjprescott** [comment]
Thanks for the quick response. When I try this, I get the following error:
```
Precondition failed: BUG DETECTED: wait() must not be called when on an EventLoop.
Calling wait() on any EventLoop can lead to
- deadlocks
- stalling processing of other connections (Channels) that are handled on the EventLoop that wait was called on

Further information:
- current eventLoop: Optional(SelectableEventLoop { selector = Selector { descriptor = 5 }, thread = NIOThread(name = NIO-ELT-0-#0), scheduledTasks = PriorityQueue(count: 1): [ScheduledTask(readyTime: 54814703572415)] })
- event loop associated to future: SelectableEventLoop { selector = Selector { descriptor = 5 }, thread = NIOThread(name = NIO-ELT-0-#0) }:
```

**Comment by Lukasa** [comment]
Yes, replace my call to `.wait` with `whenCompleteBlocking(onto: /* whatever queue you want to use */) { /* your handling code */ }`.

**Comment by Lukasa** [comment]
That is, you'd have:

```swift
channel.eventLoop.flatSubmit {
    let futures = keys.map { channel.call(method: "GetValue": params: .list([.string(session), .string($0)])) }
    return EventLoopFuture.whenAllSucceed(futures, on: channel.eventLoop)
}.whenCompleteBlocking(onto: yourDispatchQueue) { (results: Result<[Result], Error>) in 
    /* handle the results in here */
}
```

**Comment by tjprescott** [comment]
When I try this, I get the same behavior as before when I block with the `DispatchGroup` and notify `DispatchQueue.global()`. That succeeds, but the next RPC call fails:
```
Precondition failed: file /Users/.../.build/checkouts/swift-nio/Sources/NIO/ChannelPipeline.swift, line 158
```
This is an `assertInEventLoop` check. The result handling code eventually goes on to make RPC calls, so I'm assuming that's why it is failing... dispatching that block onto the global DispatchQueue takes it out of the EventLoop?

**Comment by tjprescott** [comment]
Ah, okay, here's what worked for me:
```swift
let futures = keys.map { channel.call(method: "GetValue": params: .list([.string(session), .string($0)])) }
let future = EventLoopFuture.whenAllSucceed(futures, on: channel.eventLoop)
future.whenSuccess { results in
  // update some dictionary stuff
  completion()
}
```

It's still asynchronous but it does eliminate the pyramid-of-doom which was the main sticking point. Thank you @Lukasa for all your assistance!!!
