### ISSUE TITLE
connect-proxy demo access http resource return 'Invalid HTTP message type get'

### ISSUE THREAD

**Issue by greenhaixia** [apple/swift-nio-examples#87]
when using connect proxy demo to access 'http://sns-img-hw.xhscdn.com/1040g00830ntikh5h1a005odf8lgoceh3uoecgn8?imageView2/2/w/540/format/jpg/q/75%7CimageMogr2/strip&redImage/frame/0' , the logger show Invalid HTTP message type get.

**Comment by Lukasa** [comment]
The CONNECT proxy only proxies HTTPS traffic.
